name: spatialite-gui
version: '1.7.1'
summary: an open source GUI tool supporting SpatiaLite
description: |
  spatialite-gui is an open source GUI tool supporting SpatiaLite.

base: core20

grade: devel
confinement: devmode # use 'strict' once you have the right plugs and slots
compression: lzo


apps:
  spatialite-gui:
    command: usr/local/bin/spatialite_gui
    extensions: [gnome-3-38]
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/local/lib"

parts:
  libgaiagraphics:
    plugin: autotools
    source-type: tar
    source: https://www.gaia-gis.it/gaia-sins/libgaiagraphics-0.5.tar.gz
    override-build: |
      ./configure
      make -j"${SNAPCRAFT_PARALLEL_BUILD_COUNT}"
      make install-strip DESTDIR="${SNAPCRAFT_PART_INSTALL}"

    build-packages:
      - libjpeg-dev
      - libpng-dev
      - libgeotiff-dev
      - libxml2-dev
    stage-packages:
      - libgeotiff5
      - libjpeg-turbo8
      - libpng16-16
    prime:
      - -**/*.a
      - -**/*.la
      - -**/*.pc
      - -usr/local/include/*

  spatialite-gui:
    plugin: autotools
    source-type: tar
    source: https://www.gaia-gis.it/gaia-sins/spatialite_gui-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    after: [libgaiagraphics]
    build-packages:
      - libsqlite3-dev
      - libspatialite-dev
      - libpng-dev
      - libgeotiff-dev
      - libxml2-dev
      - libgeos-dev
      - libfreexl-dev
      - libwxgtk3.0-gtk3-dev
    stage-packages:
      - libspatialite7
      - libgeotiff5
      - libwxbase3.0-0v5
      - libwxgtk3.0-gtk3-0v5

    override-pull: |
      snapcraftctl pull
      patch Makefile.am $SNAPCRAFT_PROJECT_DIR/Makefile.am.patch
      patch configure.ac $SNAPCRAFT_PROJECT_DIR/configure.ac.patch
    override-build: |
      autoconf && aclocal && automake --add-missing
      ./configure
      make -j"${SNAPCRAFT_PARALLEL_BUILD_COUNT}"
      make install-strip DESTDIR="${SNAPCRAFT_PART_INSTALL}"
    build-environment:
      - PKG_CONFIG_PATH: $SNAPCRAFT_STAGE/usr/local/lib/pkgconfig/
      - CFLAGS: "-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H"
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - libgaiagraphics
      - spatialite-gui
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core20
      - gnome-3-38-2004-sdk
    override-prime: |
      set -eux
      find . -type d -empty -prune -exec rm -rf \{} \;
      rm -rf usr/share/doc usr/share/man
      for snap in "core20" "gnome-3-38-2004"; do
          cd "/snap/$snap/current" && \
            find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
          find . -type d -empty -prune -exec rm -rf \{} \;
      done
