name: spatialite-gui
version: '1.7.1'
summary: an open source GUI tool supporting SpatiaLite
description: |
  spatialite-gui is an open source GUI tool supporting SpatiaLite.

base: core20

grade: devel
confinement: devmode # use 'strict' once you have the right plugs and slots
compression: lzo

apps:
  spatialite-gui:
    command: usr/local/bin/spatialite_gui
    extensions: [gnome-3-38]
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/local/lib"

parts:
  libgaiagraphics:
    plugin: autotools
    source-type: tar
    source: https://www.gaia-gis.it/gaia-sins/libgaiagraphics-0.5.tar.gz
    override-build: |
      ./configure
      make -j"${SNAPCRAFT_PARALLEL_BUILD_COUNT}"
      make install-strip DESTDIR="${SNAPCRAFT_PART_INSTALL}"

    build-packages:
      - libjpeg-dev
      - libpng-dev
      - libgeotiff-dev
      - libxml2-dev
    stage-packages:
      - libgeotiff5
      - libjpeg-turbo8
      - libpng16-16
    prime:
      - -**/*.a
      - -**/*.la
      - -**/*.pc
      - -usr/local/include
      - -usr/share/doc 
      - -usr/share/man

  spatialite-gui:
    plugin: autotools
    source-type: tar
    source: https://www.gaia-gis.it/gaia-sins/spatialite_gui-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    after: [libgaiagraphics]
    build-packages:
      - libsqlite3-dev
      - libspatialite-dev
      - libpng-dev
      - libgeotiff-dev
      - libxml2-dev
      - libgeos-dev
      - libfreexl-dev
      - libwxgtk3.0-gtk3-dev
    stage-packages:
      - libspatialite7
      - libgeotiff5
      - libwxbase3.0-0v5
      - libwxgtk3.0-gtk3-0v5
    prime:
      - -**/*.a
      - -**/*.la
      - -**/*.pc
      - -usr/share/doc 
      - -usr/share/man
      - -usr/lib/x86_64-linux-gnu/libpsl.so.5.3.2
      - -usr/lib/x86_64-linux-gnu/librest-0.7.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libwx_baseu_net-3.0.so.0.4.0 
      - -usr/lib/x86_64-linux-gnu/libwx_baseu_xml-3.0.so.0.4.0 
      - -usr/lib/x86_64-linux-gnu/libwx_gtk3u_gl-3.0.so.0.4.0 
      - -usr/lib/x86_64-linux-gnu/libwx_gtk3u_propgrid-3.0.so.0.4.0 
      - -usr/lib/x86_64-linux-gnu/libwx_gtk3u_qa-3.0.so.0.4.0 
      - -usr/lib/x86_64-linux-gnu/libwx_gtk3u_ribbon-3.0.so.0.4.0 
      - -usr/lib/x86_64-linux-gnu/libwx_gtk3u_richtext-3.0.so.0.4.0 
      - -usr/lib/x86_64-linux-gnu/libwx_gtk3u_stc-3.0.so.0.4.0 
      - -usr/lib/x86_64-linux-gnu/libwx_gtk3u_xrc-3.0.so.0.4.0

    override-pull: |
      snapcraftctl pull
      patch Makefile.am $SNAPCRAFT_PROJECT_DIR/Makefile.am.patch
      patch configure.ac $SNAPCRAFT_PROJECT_DIR/configure.ac.patch
    override-build: |
      autoconf && aclocal && automake --add-missing
      ./configure
      make -j"${SNAPCRAFT_PARALLEL_BUILD_COUNT}"
      make install-strip DESTDIR="${SNAPCRAFT_PART_INSTALL}"
    build-environment:
      - PKG_CONFIG_PATH: $SNAPCRAFT_STAGE/usr/local/lib/pkgconfig/
      - CFLAGS: "-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H"

  cleanup:
    after:  # Make this part run last; list all your other parts here
      - libgaiagraphics
      - spatialite-gui
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core20
      - gnome-3-38-2004-sdk
      - gtk-common-themes

    override-prime: |
      set -eux

      snaps="core20 gnome-3-38-2004"

      for snap in $snaps; do

        find "/snap/$snap/current/" -type l -name \*.so\* -printf "$SNAPCRAFT_PRIME/%P\0" \
          | xargs -0 -ri sh -c "readlink -ez {} || true" \
          | xargs -0 -r rm -rf

        find "/snap/$snap/current/" -type f,l -printf "$SNAPCRAFT_PRIME/%P\0" \
          | xargs -0 -r rm -rf
      done

      find /snap/gtk-common-themes/current/ -type f,l -printf "$SNAPCRAFT_PRIME/usr/%P\0" \
        | xargs -0 -r rm -rf

      find $SNAPCRAFT_PRIME -depth -type d -empty -delete
